clang -E \
  -xc \
  -DARM9 -DNDS -D__NDS__ -D__CALICO__ -DGBA \
  -D_REVOLUTION \
  -I/opt/devkitpro/libnds/include \
  -I/opt/devkitpro/libnds/include/nds \
  -I/opt/devkitpro/calico/include \
  -I/opt/devkitpro/calico/include/calico \
  -I/opt/devkitpro/devkitARM/arm-none-eabi/include \
  -I/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/12.2.0/include \
  -I/Users/blakemoody/dev/mariokart_ml/mkds_c/external_include \
  -I/Users/blakemoody/dev/mariokart_ml/mkds_c \
  -I/Users/blakemoody/dev/mariokart_ml/mkds_c/external_include/nitro_dwc \
  -I/Users/blakemoody/dev/mariokart_ml/mkds_c/external_include/nitro_dwc/gs \
  -I/Users/blakemoody/dev/mariokart_ml/mkds_c/external_include/nnsys \
  -I/Users/blakemoody/dev/mariokart_ml/mkds_c/external_include/nitro \
  -I/Users/blakemoody/dev/mariokart_ml/mkds_c/external_include/nitro/fx \
  -I/Users/blakemoody/dev/mariokart_ml/mkds_c/external_include/nitro/os/common \
  -I/Users/blakemoody/dev/mariokart_ml/mkds_c/external_include/nitroWiFi \
  -I/Users/blakemoody/dev/mariokart_ml/mkds_c/race \
  -include /opt/devkitpro/libnds/include/nds.h \
  -include nds.h \
  -include nnsys.h \
  -include nitro_sp.h \
  -include dwc.h \
  -include nitroWiFi.h \
  -include ninet.h \
  -include /Users/blakemoody/dev/mariokart_ml/mkds_c/input/pad.h \
  -include /Users/blakemoody/dev/mariokart_ml/mkds_c/snd/microphone.h \
  -include /Users/blakemoody/dev/mariokart_ml/mkds_c/external_include/malloc.h \
  /Users/blakemoody/dev/mariokart_ml/mkds_c/race/drivers/driver.h > driver_out.h