from ctypes import *
from private.mkds_python_bindings.testing.animator import *
from private.mkds_python_bindings.testing.fx import *
from private.mkds_python_bindings.testing.model import *
from private.mkds_python_bindings.testing.types import *

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

ANIM_KIND_JNT = 0
ANIM_KIND_SRT = 1
ANIM_KIND_PAT = 2
ANIM_KIND_VIS = 3
ANIM_KIND_MAT = 4

AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int
AnimKind = c_int


class anim_manager_t(Structure):
    _fields_ = [
        ('animator', anim_animator_t),
        ('model', u32), #POINTER(model_t)),
        ('animCount', u16),
        ('curAnimIdx', u16),
        ('anmObjs', u32), #POINTER(POINTER(c_int))),
        ('loopFlags', u32), #POINTER(BOOL)),
        ('field24', u32),
        ('animKind', AnimKind),
        ('isBlending', BOOL),
        ('blendSpeed', fx32),
        ('blendAnmObj', u32), #POINTER(c_int)),
    ]
