from ctypes import *
from private.mkds_python_bindings.testing.fx import *
from private.mkds_python_bindings.testing.types import *

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

ANIM_LOOP_MODE_STOP = 0
ANIM_LOOP_MODE_INFINITE_LOOP = 1
ANIM_LOOP_MODE_COUNTED_LOOP = 2

AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int
AnimLoopMode = c_int


class anim_animator_t(Structure):
    _fields_ = [
        ('loopMode', u16),
        ('hasEnded', u16),
        ('animLength', fx32),
        ('speed', fx32),
        ('progress', fx32),
        ('loopIteration', u16),
        ('loopCount', u16),
    ]
