from ctypes import *
SND_CAPTURE_0 = 0
SND_CAPTURE_1 = 1

SND_CAPTURE_0 = 0
SND_CAPTURE_1 = 1

SND_CAPTURE_FORMAT_PCM16 = 0
SND_CAPTURE_FORMAT_PCM8 = 1

SND_CAPTURE_FORMAT_PCM16 = 0
SND_CAPTURE_FORMAT_PCM8 = 1

SND_CAPTURE_REPEAT_YES = 0
SND_CAPTURE_REPEAT_NO = 1

SND_CAPTURE_REPEAT_YES = 0
SND_CAPTURE_REPEAT_NO = 1

SND_CAPTURE_IN_MIXER = 0
SND_CAPTURE_IN_CHANNEL = 1
SND_CAPTURE_IN_MIXER_L = 0
SND_CAPTURE_IN_MIXER_R = 0
SND_CAPTURE_IN_CHANNEL0 = 1
SND_CAPTURE_IN_CHANNEL2 = 1

SND_CAPTURE_IN_MIXER = 0
SND_CAPTURE_IN_CHANNEL = 1
SND_CAPTURE_IN_MIXER_L = 0
SND_CAPTURE_IN_MIXER_R = 0
SND_CAPTURE_IN_CHANNEL0 = 1
SND_CAPTURE_IN_CHANNEL2 = 1

SND_CAPTURE_OUT_NORMAL = 0
SND_CAPTURE_OUT_CHANNEL_MIX = 1
SND_CAPTURE_OUT_CHANNEL0_MIX = 1
SND_CAPTURE_OUT_CHANNEL2_MIX = 1

SND_CAPTURE_OUT_NORMAL = 0
SND_CAPTURE_OUT_CHANNEL_MIX = 1
SND_CAPTURE_OUT_CHANNEL0_MIX = 1
SND_CAPTURE_OUT_CHANNEL2_MIX = 1

SNDCapture = c_int
SNDCaptureFormat = c_int
SNDCaptureIn = c_int
SNDCaptureOut = c_int
SNDCaptureRepeat = c_int

