from ctypes import *
from private.mkds_python_bindings.testing.fx import *
from private.mkds_python_bindings.testing.types import *

COL_TYPE_ROAD = 0
COL_TYPE_SLIPPERY_ROAD = 1
COL_TYPE_WEAK_OFF_ROAD = 2
COL_TYPE_OFF_ROAD = 3
COL_TYPE_SOUND_TRIGGER = 4
COL_TYPE_HEAVY_OFF_ROAD = 5
COL_TYPE_SLIPPERY_ROAD_2 = 6
COL_TYPE_BOOST_PAD = 7
COL_TYPE_WALL = 8
COL_TYPE_INVISIBLE_WALL = 9
COL_TYPE_OUT_OF_BOUNDS = 10
COL_TYPE_FALL_BOUNDARY = 11
COL_TYPE_JUMP_PAD = 12
COL_TYPE_ROAD_NO_DRIVERS = 13
COL_TYPE_WALL_NO_DRIVERS = 14
COL_TYPE_CANNON_ACTIVATOR = 15
COL_TYPE_EDGE_WALL = 16
COL_TYPE_FALLS_WATER = 17
COL_TYPE_BOOST_PAD_MIN_SPEED = 18
COL_TYPE_LOOPING = 19
COL_TYPE_SPECIAL_ROAD = 20
COL_TYPE_WALL_3 = 21
COL_TYPE_FORCE_RECALCULATE_ROUTE = 22
COL_TYPE_COUNT = 23

COL_TYPE_ROAD = 0
COL_TYPE_SLIPPERY_ROAD = 1
COL_TYPE_WEAK_OFF_ROAD = 2
COL_TYPE_OFF_ROAD = 3
COL_TYPE_SOUND_TRIGGER = 4
COL_TYPE_HEAVY_OFF_ROAD = 5
COL_TYPE_SLIPPERY_ROAD_2 = 6
COL_TYPE_BOOST_PAD = 7
COL_TYPE_WALL = 8
COL_TYPE_INVISIBLE_WALL = 9
COL_TYPE_OUT_OF_BOUNDS = 10
COL_TYPE_FALL_BOUNDARY = 11
COL_TYPE_JUMP_PAD = 12
COL_TYPE_ROAD_NO_DRIVERS = 13
COL_TYPE_WALL_NO_DRIVERS = 14
COL_TYPE_CANNON_ACTIVATOR = 15
COL_TYPE_EDGE_WALL = 16
COL_TYPE_FALLS_WATER = 17
COL_TYPE_BOOST_PAD_MIN_SPEED = 18
COL_TYPE_LOOPING = 19
COL_TYPE_SPECIAL_ROAD = 20
COL_TYPE_WALL_3 = 21
COL_TYPE_FORCE_RECALCULATE_ROUTE = 22
COL_TYPE_COUNT = 23

COL_TYPE_ROAD = 0
COL_TYPE_SLIPPERY_ROAD = 1
COL_TYPE_WEAK_OFF_ROAD = 2
COL_TYPE_OFF_ROAD = 3
COL_TYPE_SOUND_TRIGGER = 4
COL_TYPE_HEAVY_OFF_ROAD = 5
COL_TYPE_SLIPPERY_ROAD_2 = 6
COL_TYPE_BOOST_PAD = 7
COL_TYPE_WALL = 8
COL_TYPE_INVISIBLE_WALL = 9
COL_TYPE_OUT_OF_BOUNDS = 10
COL_TYPE_FALL_BOUNDARY = 11
COL_TYPE_JUMP_PAD = 12
COL_TYPE_ROAD_NO_DRIVERS = 13
COL_TYPE_WALL_NO_DRIVERS = 14
COL_TYPE_CANNON_ACTIVATOR = 15
COL_TYPE_EDGE_WALL = 16
COL_TYPE_FALLS_WATER = 17
COL_TYPE_BOOST_PAD_MIN_SPEED = 18
COL_TYPE_LOOPING = 19
COL_TYPE_SPECIAL_ROAD = 20
COL_TYPE_WALL_3 = 21
COL_TYPE_FORCE_RECALCULATE_ROUTE = 22
COL_TYPE_COUNT = 23

COL_TYPE_ROAD = 0
COL_TYPE_SLIPPERY_ROAD = 1
COL_TYPE_WEAK_OFF_ROAD = 2
COL_TYPE_OFF_ROAD = 3
COL_TYPE_SOUND_TRIGGER = 4
COL_TYPE_HEAVY_OFF_ROAD = 5
COL_TYPE_SLIPPERY_ROAD_2 = 6
COL_TYPE_BOOST_PAD = 7
COL_TYPE_WALL = 8
COL_TYPE_INVISIBLE_WALL = 9
COL_TYPE_OUT_OF_BOUNDS = 10
COL_TYPE_FALL_BOUNDARY = 11
COL_TYPE_JUMP_PAD = 12
COL_TYPE_ROAD_NO_DRIVERS = 13
COL_TYPE_WALL_NO_DRIVERS = 14
COL_TYPE_CANNON_ACTIVATOR = 15
COL_TYPE_EDGE_WALL = 16
COL_TYPE_FALLS_WATER = 17
COL_TYPE_BOOST_PAD_MIN_SPEED = 18
COL_TYPE_LOOPING = 19
COL_TYPE_SPECIAL_ROAD = 20
COL_TYPE_WALL_3 = 21
COL_TYPE_FORCE_RECALCULATE_ROUTE = 22
COL_TYPE_COUNT = 23

COL_TYPE_ROAD = 0
COL_TYPE_SLIPPERY_ROAD = 1
COL_TYPE_WEAK_OFF_ROAD = 2
COL_TYPE_OFF_ROAD = 3
COL_TYPE_SOUND_TRIGGER = 4
COL_TYPE_HEAVY_OFF_ROAD = 5
COL_TYPE_SLIPPERY_ROAD_2 = 6
COL_TYPE_BOOST_PAD = 7
COL_TYPE_WALL = 8
COL_TYPE_INVISIBLE_WALL = 9
COL_TYPE_OUT_OF_BOUNDS = 10
COL_TYPE_FALL_BOUNDARY = 11
COL_TYPE_JUMP_PAD = 12
COL_TYPE_ROAD_NO_DRIVERS = 13
COL_TYPE_WALL_NO_DRIVERS = 14
COL_TYPE_CANNON_ACTIVATOR = 15
COL_TYPE_EDGE_WALL = 16
COL_TYPE_FALLS_WATER = 17
COL_TYPE_BOOST_PAD_MIN_SPEED = 18
COL_TYPE_LOOPING = 19
COL_TYPE_SPECIAL_ROAD = 20
COL_TYPE_WALL_3 = 21
COL_TYPE_FORCE_RECALCULATE_ROUTE = 22
COL_TYPE_COUNT = 23

COL_TYPE_ROAD = 0
COL_TYPE_SLIPPERY_ROAD = 1
COL_TYPE_WEAK_OFF_ROAD = 2
COL_TYPE_OFF_ROAD = 3
COL_TYPE_SOUND_TRIGGER = 4
COL_TYPE_HEAVY_OFF_ROAD = 5
COL_TYPE_SLIPPERY_ROAD_2 = 6
COL_TYPE_BOOST_PAD = 7
COL_TYPE_WALL = 8
COL_TYPE_INVISIBLE_WALL = 9
COL_TYPE_OUT_OF_BOUNDS = 10
COL_TYPE_FALL_BOUNDARY = 11
COL_TYPE_JUMP_PAD = 12
COL_TYPE_ROAD_NO_DRIVERS = 13
COL_TYPE_WALL_NO_DRIVERS = 14
COL_TYPE_CANNON_ACTIVATOR = 15
COL_TYPE_EDGE_WALL = 16
COL_TYPE_FALLS_WATER = 17
COL_TYPE_BOOST_PAD_MIN_SPEED = 18
COL_TYPE_LOOPING = 19
COL_TYPE_SPECIAL_ROAD = 20
COL_TYPE_WALL_3 = 21
COL_TYPE_FORCE_RECALCULATE_ROUTE = 22
COL_TYPE_COUNT = 23

COL_TYPE_ROAD = 0
COL_TYPE_SLIPPERY_ROAD = 1
COL_TYPE_WEAK_OFF_ROAD = 2
COL_TYPE_OFF_ROAD = 3
COL_TYPE_SOUND_TRIGGER = 4
COL_TYPE_HEAVY_OFF_ROAD = 5
COL_TYPE_SLIPPERY_ROAD_2 = 6
COL_TYPE_BOOST_PAD = 7
COL_TYPE_WALL = 8
COL_TYPE_INVISIBLE_WALL = 9
COL_TYPE_OUT_OF_BOUNDS = 10
COL_TYPE_FALL_BOUNDARY = 11
COL_TYPE_JUMP_PAD = 12
COL_TYPE_ROAD_NO_DRIVERS = 13
COL_TYPE_WALL_NO_DRIVERS = 14
COL_TYPE_CANNON_ACTIVATOR = 15
COL_TYPE_EDGE_WALL = 16
COL_TYPE_FALLS_WATER = 17
COL_TYPE_BOOST_PAD_MIN_SPEED = 18
COL_TYPE_LOOPING = 19
COL_TYPE_SPECIAL_ROAD = 20
COL_TYPE_WALL_3 = 21
COL_TYPE_FORCE_RECALCULATE_ROUTE = 22
COL_TYPE_COUNT = 23

COL_TYPE_ROAD = 0
COL_TYPE_SLIPPERY_ROAD = 1
COL_TYPE_WEAK_OFF_ROAD = 2
COL_TYPE_OFF_ROAD = 3
COL_TYPE_SOUND_TRIGGER = 4
COL_TYPE_HEAVY_OFF_ROAD = 5
COL_TYPE_SLIPPERY_ROAD_2 = 6
COL_TYPE_BOOST_PAD = 7
COL_TYPE_WALL = 8
COL_TYPE_INVISIBLE_WALL = 9
COL_TYPE_OUT_OF_BOUNDS = 10
COL_TYPE_FALL_BOUNDARY = 11
COL_TYPE_JUMP_PAD = 12
COL_TYPE_ROAD_NO_DRIVERS = 13
COL_TYPE_WALL_NO_DRIVERS = 14
COL_TYPE_CANNON_ACTIVATOR = 15
COL_TYPE_EDGE_WALL = 16
COL_TYPE_FALLS_WATER = 17
COL_TYPE_BOOST_PAD_MIN_SPEED = 18
COL_TYPE_LOOPING = 19
COL_TYPE_SPECIAL_ROAD = 20
COL_TYPE_WALL_3 = 21
COL_TYPE_FORCE_RECALCULATE_ROUTE = 22
COL_TYPE_COUNT = 23

COL_TYPE_ROAD = 0
COL_TYPE_SLIPPERY_ROAD = 1
COL_TYPE_WEAK_OFF_ROAD = 2
COL_TYPE_OFF_ROAD = 3
COL_TYPE_SOUND_TRIGGER = 4
COL_TYPE_HEAVY_OFF_ROAD = 5
COL_TYPE_SLIPPERY_ROAD_2 = 6
COL_TYPE_BOOST_PAD = 7
COL_TYPE_WALL = 8
COL_TYPE_INVISIBLE_WALL = 9
COL_TYPE_OUT_OF_BOUNDS = 10
COL_TYPE_FALL_BOUNDARY = 11
COL_TYPE_JUMP_PAD = 12
COL_TYPE_ROAD_NO_DRIVERS = 13
COL_TYPE_WALL_NO_DRIVERS = 14
COL_TYPE_CANNON_ACTIVATOR = 15
COL_TYPE_EDGE_WALL = 16
COL_TYPE_FALLS_WATER = 17
COL_TYPE_BOOST_PAD_MIN_SPEED = 18
COL_TYPE_LOOPING = 19
COL_TYPE_SPECIAL_ROAD = 20
COL_TYPE_WALL_3 = 21
COL_TYPE_FORCE_RECALCULATE_ROUTE = 22
COL_TYPE_COUNT = 23

COL_TYPE_ROAD = 0
COL_TYPE_SLIPPERY_ROAD = 1
COL_TYPE_WEAK_OFF_ROAD = 2
COL_TYPE_OFF_ROAD = 3
COL_TYPE_SOUND_TRIGGER = 4
COL_TYPE_HEAVY_OFF_ROAD = 5
COL_TYPE_SLIPPERY_ROAD_2 = 6
COL_TYPE_BOOST_PAD = 7
COL_TYPE_WALL = 8
COL_TYPE_INVISIBLE_WALL = 9
COL_TYPE_OUT_OF_BOUNDS = 10
COL_TYPE_FALL_BOUNDARY = 11
COL_TYPE_JUMP_PAD = 12
COL_TYPE_ROAD_NO_DRIVERS = 13
COL_TYPE_WALL_NO_DRIVERS = 14
COL_TYPE_CANNON_ACTIVATOR = 15
COL_TYPE_EDGE_WALL = 16
COL_TYPE_FALLS_WATER = 17
COL_TYPE_BOOST_PAD_MIN_SPEED = 18
COL_TYPE_LOOPING = 19
COL_TYPE_SPECIAL_ROAD = 20
COL_TYPE_WALL_3 = 21
COL_TYPE_FORCE_RECALCULATE_ROUTE = 22
COL_TYPE_COUNT = 23

COL_TYPE_ROAD = 0
COL_TYPE_SLIPPERY_ROAD = 1
COL_TYPE_WEAK_OFF_ROAD = 2
COL_TYPE_OFF_ROAD = 3
COL_TYPE_SOUND_TRIGGER = 4
COL_TYPE_HEAVY_OFF_ROAD = 5
COL_TYPE_SLIPPERY_ROAD_2 = 6
COL_TYPE_BOOST_PAD = 7
COL_TYPE_WALL = 8
COL_TYPE_INVISIBLE_WALL = 9
COL_TYPE_OUT_OF_BOUNDS = 10
COL_TYPE_FALL_BOUNDARY = 11
COL_TYPE_JUMP_PAD = 12
COL_TYPE_ROAD_NO_DRIVERS = 13
COL_TYPE_WALL_NO_DRIVERS = 14
COL_TYPE_CANNON_ACTIVATOR = 15
COL_TYPE_EDGE_WALL = 16
COL_TYPE_FALLS_WATER = 17
COL_TYPE_BOOST_PAD_MIN_SPEED = 18
COL_TYPE_LOOPING = 19
COL_TYPE_SPECIAL_ROAD = 20
COL_TYPE_WALL_3 = 21
COL_TYPE_FORCE_RECALCULATE_ROUTE = 22
COL_TYPE_COUNT = 23

COL_TYPE_ROAD = 0
COL_TYPE_SLIPPERY_ROAD = 1
COL_TYPE_WEAK_OFF_ROAD = 2
COL_TYPE_OFF_ROAD = 3
COL_TYPE_SOUND_TRIGGER = 4
COL_TYPE_HEAVY_OFF_ROAD = 5
COL_TYPE_SLIPPERY_ROAD_2 = 6
COL_TYPE_BOOST_PAD = 7
COL_TYPE_WALL = 8
COL_TYPE_INVISIBLE_WALL = 9
COL_TYPE_OUT_OF_BOUNDS = 10
COL_TYPE_FALL_BOUNDARY = 11
COL_TYPE_JUMP_PAD = 12
COL_TYPE_ROAD_NO_DRIVERS = 13
COL_TYPE_WALL_NO_DRIVERS = 14
COL_TYPE_CANNON_ACTIVATOR = 15
COL_TYPE_EDGE_WALL = 16
COL_TYPE_FALLS_WATER = 17
COL_TYPE_BOOST_PAD_MIN_SPEED = 18
COL_TYPE_LOOPING = 19
COL_TYPE_SPECIAL_ROAD = 20
COL_TYPE_WALL_3 = 21
COL_TYPE_FORCE_RECALCULATE_ROUTE = 22
COL_TYPE_COUNT = 23

COL_TYPE_ROAD = 0
COL_TYPE_SLIPPERY_ROAD = 1
COL_TYPE_WEAK_OFF_ROAD = 2
COL_TYPE_OFF_ROAD = 3
COL_TYPE_SOUND_TRIGGER = 4
COL_TYPE_HEAVY_OFF_ROAD = 5
COL_TYPE_SLIPPERY_ROAD_2 = 6
COL_TYPE_BOOST_PAD = 7
COL_TYPE_WALL = 8
COL_TYPE_INVISIBLE_WALL = 9
COL_TYPE_OUT_OF_BOUNDS = 10
COL_TYPE_FALL_BOUNDARY = 11
COL_TYPE_JUMP_PAD = 12
COL_TYPE_ROAD_NO_DRIVERS = 13
COL_TYPE_WALL_NO_DRIVERS = 14
COL_TYPE_CANNON_ACTIVATOR = 15
COL_TYPE_EDGE_WALL = 16
COL_TYPE_FALLS_WATER = 17
COL_TYPE_BOOST_PAD_MIN_SPEED = 18
COL_TYPE_LOOPING = 19
COL_TYPE_SPECIAL_ROAD = 20
COL_TYPE_WALL_3 = 21
COL_TYPE_FORCE_RECALCULATE_ROUTE = 22
COL_TYPE_COUNT = 23

COL_TYPE_ROAD = 0
COL_TYPE_SLIPPERY_ROAD = 1
COL_TYPE_WEAK_OFF_ROAD = 2
COL_TYPE_OFF_ROAD = 3
COL_TYPE_SOUND_TRIGGER = 4
COL_TYPE_HEAVY_OFF_ROAD = 5
COL_TYPE_SLIPPERY_ROAD_2 = 6
COL_TYPE_BOOST_PAD = 7
COL_TYPE_WALL = 8
COL_TYPE_INVISIBLE_WALL = 9
COL_TYPE_OUT_OF_BOUNDS = 10
COL_TYPE_FALL_BOUNDARY = 11
COL_TYPE_JUMP_PAD = 12
COL_TYPE_ROAD_NO_DRIVERS = 13
COL_TYPE_WALL_NO_DRIVERS = 14
COL_TYPE_CANNON_ACTIVATOR = 15
COL_TYPE_EDGE_WALL = 16
COL_TYPE_FALLS_WATER = 17
COL_TYPE_BOOST_PAD_MIN_SPEED = 18
COL_TYPE_LOOPING = 19
COL_TYPE_SPECIAL_ROAD = 20
COL_TYPE_WALL_3 = 21
COL_TYPE_FORCE_RECALCULATE_ROUTE = 22
COL_TYPE_COUNT = 23

ColType = c_int
ColType = c_int
ColType = c_int
ColType = c_int
ColType = c_int
ColType = c_int
ColType = c_int


class col_response_t(Structure):
    _fields_ = [
        ('maxSomething', VecFx32),
        ('minSomething', VecFx32),
        ('distance', fx32),
        ('normal', VecFx32),
    ]

class col_segment_left_endpoint_t(Structure):
    _fields_ = [
        ('rightEndpoint', u8),
        ('colEntryId', u8),
        ('xPos', s16),
    ]

class col_segment_right_endpoint_t(Structure):
    _fields_ = [
        ('leftEndpoint', u8),
        ('minLeftEndpoint', u8),
        ('xPos', s16),
    ]

class col_entry_t(Structure):
    _fields_ = [
        ('segmentRightEndpoint', s16),
        ('segmentLeftEndpoint', s16),
        ('zMax', fx32),
        ('zMin', fx32),
        ('position', u32), #POINTER(VecFx32)),
        ('boundingSphereRadius', fx32),
        ('flags', u16),
        ('object', u32),
    ]
