from ctypes import *
CSFX_FLOOR_MAT_ASPHALT = 0
CSFX_FLOOR_MAT_CONCRETE = 1
CSFX_FLOOR_MAT_EDGE = 2
CSFX_FLOOR_MAT_DIRT = 3
CSFX_FLOOR_MAT_STONE = 4
CSFX_FLOOR_MAT_SAND = 5
CSFX_FLOOR_MAT_ICE = 6
CSFX_FLOOR_MAT_GRASS = 7
CSFX_FLOOR_MAT_WATER = 8
CSFX_FLOOR_MAT_SNOW = 9
CSFX_FLOOR_MAT_BOARD = 10
CSFX_FLOOR_MAT_CARPET = 11
CSFX_FLOOR_MAT_KANAAMI = 12
CSFX_FLOOR_MAT_PLASTIC = 13
CSFX_FLOOR_MAT_TEPPAN = 14
CSFX_FLOOR_MAT_RAINBOW = 15
CSFX_FLOOR_MAT_DORONUMA = 16
CSFX_FLOOR_MAT_KAIDAN = 17
CSFX_FLOOR_MAT_18 = 18
CSFX_FLOOR_MAT_COUNT = 19
CSFX_FLOOR_MAT_INVALID_19 = 19
CSFX_FLOOR_MAT_NONE = 20

CSFX_FLOOR_MAT_ASPHALT = 0
CSFX_FLOOR_MAT_CONCRETE = 1
CSFX_FLOOR_MAT_EDGE = 2
CSFX_FLOOR_MAT_DIRT = 3
CSFX_FLOOR_MAT_STONE = 4
CSFX_FLOOR_MAT_SAND = 5
CSFX_FLOOR_MAT_ICE = 6
CSFX_FLOOR_MAT_GRASS = 7
CSFX_FLOOR_MAT_WATER = 8
CSFX_FLOOR_MAT_SNOW = 9
CSFX_FLOOR_MAT_BOARD = 10
CSFX_FLOOR_MAT_CARPET = 11
CSFX_FLOOR_MAT_KANAAMI = 12
CSFX_FLOOR_MAT_PLASTIC = 13
CSFX_FLOOR_MAT_TEPPAN = 14
CSFX_FLOOR_MAT_RAINBOW = 15
CSFX_FLOOR_MAT_DORONUMA = 16
CSFX_FLOOR_MAT_KAIDAN = 17
CSFX_FLOOR_MAT_18 = 18
CSFX_FLOOR_MAT_COUNT = 19
CSFX_FLOOR_MAT_INVALID_19 = 19
CSFX_FLOOR_MAT_NONE = 20

CSFX_WALL_MAT_CONCRETE = 0
CSFX_WALL_MAT_FENCE = 1
CSFX_WALL_MAT_WOOD = 2
CSFX_WALL_MAT_TREE = 3
CSFX_WALL_MAT_SHIGEMI = 4
CSFX_WALL_MAT_GAKE = 5
CSFX_WALL_MAT_KANBAN = 6
CSFX_WALL_MAT_ICEWALL = 7
CSFX_WALL_MAT_SNOWROCK = 8
CSFX_WALL_MAT_TABLE = 9
CSFX_WALL_MAT_UKIWA = 10
CSFX_WALL_MAT_JELLY = 11
CSFX_WALL_MAT_KANAAMI = 12
CSFX_WALL_MAT_COUNT = 13
CSFX_WALL_MAT_NONE = 14

CSFX_WALL_MAT_CONCRETE = 0
CSFX_WALL_MAT_FENCE = 1
CSFX_WALL_MAT_WOOD = 2
CSFX_WALL_MAT_TREE = 3
CSFX_WALL_MAT_SHIGEMI = 4
CSFX_WALL_MAT_GAKE = 5
CSFX_WALL_MAT_KANBAN = 6
CSFX_WALL_MAT_ICEWALL = 7
CSFX_WALL_MAT_SNOWROCK = 8
CSFX_WALL_MAT_TABLE = 9
CSFX_WALL_MAT_UKIWA = 10
CSFX_WALL_MAT_JELLY = 11
CSFX_WALL_MAT_KANAAMI = 12
CSFX_WALL_MAT_COUNT = 13
CSFX_WALL_MAT_NONE = 14

CSFX_FLOOR_SFX_TYPE_RUN = 0
CSFX_FLOOR_SFX_TYPE_SLIP = 1
CSFX_FLOOR_SFX_TYPE_CHAKUCHI = 2
CSFX_FLOOR_SFX_TYPE_BRAKE = 3
CSFX_FLOOR_SFX_TYPE_COUNT = 4

CSFX_FLOOR_SFX_TYPE_RUN = 0
CSFX_FLOOR_SFX_TYPE_SLIP = 1
CSFX_FLOOR_SFX_TYPE_CHAKUCHI = 2
CSFX_FLOOR_SFX_TYPE_BRAKE = 3
CSFX_FLOOR_SFX_TYPE_COUNT = 4

CSFX_WALL_SFX_TYPE_CRUSH = 0
CSFX_WALL_SFX_TYPE_COUNT = 1

CSFX_WALL_SFX_TYPE_CRUSH = 0
CSFX_WALL_SFX_TYPE_COUNT = 1

CSfxFloorMat = c_int
CSfxFloorSfxType = c_int
CSfxWallMat = c_int
CSfxWallSfxType = c_int

