from ctypes import *
from private.mkds_python_bindings.testing.types import *

SND_COMMAND_START_SEQ = 0
SND_COMMAND_STOP_SEQ = 1
SND_COMMAND_PREPARE_SEQ = 2
SND_COMMAND_START_PREPARED_SEQ = 3
SND_COMMAND_PAUSE_SEQ = 4
SND_COMMAND_SKIP_SEQ = 5
SND_COMMAND_PLAYER_PARAM = 6
SND_COMMAND_TRACK_PARAM = 7
SND_COMMAND_MUTE_TRACK = 8
SND_COMMAND_ALLOCATABLE_CHANNEL = 9
SND_COMMAND_PLAYER_LOCAL_VAR = 10
SND_COMMAND_PLAYER_GLOBAL_VAR = 11
SND_COMMAND_START_TIMER = 12
SND_COMMAND_STOP_TIMER = 13
SND_COMMAND_SETUP_CHANNEL_PCM = 14
SND_COMMAND_SETUP_CHANNEL_PSG = 15
SND_COMMAND_SETUP_CHANNEL_NOISE = 16
SND_COMMAND_SETUP_CAPTURE = 17
SND_COMMAND_SETUP_ALARM = 18
SND_COMMAND_CHANNEL_TIMER = 19
SND_COMMAND_CHANNEL_VOLUME = 20
SND_COMMAND_CHANNEL_PAN = 21
SND_COMMAND_SURROUND_DECAY = 22
SND_COMMAND_MASTER_VOLUME = 23
SND_COMMAND_MASTER_PAN = 24
SND_COMMAND_OUTPUT_SELECTOR = 25
SND_COMMAND_LOCK_CHANNEL = 26
SND_COMMAND_UNLOCK_CHANNEL = 27
SND_COMMAND_STOP_UNLOCKED_CHANNEL = 28
SND_COMMAND_SHARED_WORK = 29
SND_COMMAND_INVALIDATE_SEQ = 30
SND_COMMAND_INVALIDATE_BANK = 31
SND_COMMAND_INVALIDATE_WAVE = 32
SND_COMMAND_READ_DRIVER_INFO = 33

SND_COMMAND_START_SEQ = 0
SND_COMMAND_STOP_SEQ = 1
SND_COMMAND_PREPARE_SEQ = 2
SND_COMMAND_START_PREPARED_SEQ = 3
SND_COMMAND_PAUSE_SEQ = 4
SND_COMMAND_SKIP_SEQ = 5
SND_COMMAND_PLAYER_PARAM = 6
SND_COMMAND_TRACK_PARAM = 7
SND_COMMAND_MUTE_TRACK = 8
SND_COMMAND_ALLOCATABLE_CHANNEL = 9
SND_COMMAND_PLAYER_LOCAL_VAR = 10
SND_COMMAND_PLAYER_GLOBAL_VAR = 11
SND_COMMAND_START_TIMER = 12
SND_COMMAND_STOP_TIMER = 13
SND_COMMAND_SETUP_CHANNEL_PCM = 14
SND_COMMAND_SETUP_CHANNEL_PSG = 15
SND_COMMAND_SETUP_CHANNEL_NOISE = 16
SND_COMMAND_SETUP_CAPTURE = 17
SND_COMMAND_SETUP_ALARM = 18
SND_COMMAND_CHANNEL_TIMER = 19
SND_COMMAND_CHANNEL_VOLUME = 20
SND_COMMAND_CHANNEL_PAN = 21
SND_COMMAND_SURROUND_DECAY = 22
SND_COMMAND_MASTER_VOLUME = 23
SND_COMMAND_MASTER_PAN = 24
SND_COMMAND_OUTPUT_SELECTOR = 25
SND_COMMAND_LOCK_CHANNEL = 26
SND_COMMAND_UNLOCK_CHANNEL = 27
SND_COMMAND_STOP_UNLOCKED_CHANNEL = 28
SND_COMMAND_SHARED_WORK = 29
SND_COMMAND_INVALIDATE_SEQ = 30
SND_COMMAND_INVALIDATE_BANK = 31
SND_COMMAND_INVALIDATE_WAVE = 32
SND_COMMAND_READ_DRIVER_INFO = 33

SNDCommandID = c_int


class SNDCommand(Structure):
    _fields_ = [
        ('next', u32), #POINTER(SNDCommand)),
        ('id', SNDCommandID),
        ('arg', (u32 * 4)),
    ]
