from ctypes import *
DRIVER_HIT_COL_REACTION_NONE = 0
DRIVER_HIT_COL_REACTION_1 = 1
DRIVER_HIT_COL_REACTION_2 = 2
DRIVER_HIT_COL_REACTION_SINGLE_SPIN_OUT = 3
DRIVER_HIT_COL_REACTION_DOUBLE_SPIN_OUT = 4
DRIVER_HIT_COL_REACTION_DOUBLE_SPIN_OUT_FIRE = 5
DRIVER_HIT_COL_REACTION_DOUBLE_SPIN_OUT_WATER = 6
DRIVER_HIT_COL_REACTION_FORWARD_FLIP = 7
DRIVER_HIT_COL_REACTION_SINGLE_BACKWARD_FLIP_1 = 8
DRIVER_HIT_COL_REACTION_SINGLE_BACKWARD_FLIP_2 = 9
DRIVER_HIT_COL_REACTION_DOUBLE_BACKWARD_FLIP = 10
DRIVER_HIT_COL_REACTION_DOSSUN_SMASH = 11
DRIVER_HIT_COL_REACTION_12 = 12
DRIVER_HIT_COL_REACTION_13 = 13
DRIVER_HIT_COL_REACTION_SINGLE_SPIN_ELECTRICITY = 14

DRIVER_HIT_COL_REACTION_NONE = 0
DRIVER_HIT_COL_REACTION_1 = 1
DRIVER_HIT_COL_REACTION_2 = 2
DRIVER_HIT_COL_REACTION_SINGLE_SPIN_OUT = 3
DRIVER_HIT_COL_REACTION_DOUBLE_SPIN_OUT = 4
DRIVER_HIT_COL_REACTION_DOUBLE_SPIN_OUT_FIRE = 5
DRIVER_HIT_COL_REACTION_DOUBLE_SPIN_OUT_WATER = 6
DRIVER_HIT_COL_REACTION_FORWARD_FLIP = 7
DRIVER_HIT_COL_REACTION_SINGLE_BACKWARD_FLIP_1 = 8
DRIVER_HIT_COL_REACTION_SINGLE_BACKWARD_FLIP_2 = 9
DRIVER_HIT_COL_REACTION_DOUBLE_BACKWARD_FLIP = 10
DRIVER_HIT_COL_REACTION_DOSSUN_SMASH = 11
DRIVER_HIT_COL_REACTION_12 = 12
DRIVER_HIT_COL_REACTION_13 = 13
DRIVER_HIT_COL_REACTION_SINGLE_SPIN_ELECTRICITY = 14

DriverHitColReaction = c_int
driver_handle_reaction_func_t = u32
driver_init_reaction_func_t = u32
driver_off_217AC14_t = u32

