from ctypes import *
from private.mkds_python_bindings.testing.types import *

RTC_PXI_RESULT_SUCCESS = 0
RTC_PXI_RESULT_INVALID_COMMAND = 1
RTC_PXI_RESULT_ILLEGAL_STATUS = 2
RTC_PXI_RESULT_BUSY = 3
RTC_PXI_RESULT_FATAL_ERROR = 4
RTC_PXI_RESULT_MAX = 5

RTC_PXI_RESULT_SUCCESS = 0
RTC_PXI_RESULT_INVALID_COMMAND = 1
RTC_PXI_RESULT_ILLEGAL_STATUS = 2
RTC_PXI_RESULT_BUSY = 3
RTC_PXI_RESULT_FATAL_ERROR = 4
RTC_PXI_RESULT_MAX = 5

PXI_FIFO_TAG_EX = 0
PXI_FIFO_TAG_USER_0 = 1
PXI_FIFO_TAG_USER_1 = 2
PXI_FIFO_TAG_SYSTEM = 3
PXI_FIFO_TAG_NVRAM = 4
PXI_FIFO_TAG_RTC = 5
PXI_FIFO_TAG_TOUCHPANEL = 6
PXI_FIFO_TAG_SOUND = 7
PXI_FIFO_TAG_PM = 8
PXI_FIFO_TAG_MIC = 9
PXI_FIFO_TAG_WM = 10
PXI_FIFO_TAG_FS = 11
PXI_FIFO_TAG_OS = 12
PXI_FIFO_TAG_CTRDG = 13
PXI_FIFO_TAG_CARD = 14
PXI_FIFO_TAG_WVR = 15
PXI_FIFO_TAG_CTRDG_Ex = 16
PXI_MAX_FIFO_TAG = 32

PXI_FIFO_TAG_EX = 0
PXI_FIFO_TAG_USER_0 = 1
PXI_FIFO_TAG_USER_1 = 2
PXI_FIFO_TAG_SYSTEM = 3
PXI_FIFO_TAG_NVRAM = 4
PXI_FIFO_TAG_RTC = 5
PXI_FIFO_TAG_TOUCHPANEL = 6
PXI_FIFO_TAG_SOUND = 7
PXI_FIFO_TAG_PM = 8
PXI_FIFO_TAG_MIC = 9
PXI_FIFO_TAG_WM = 10
PXI_FIFO_TAG_FS = 11
PXI_FIFO_TAG_OS = 12
PXI_FIFO_TAG_CTRDG = 13
PXI_FIFO_TAG_CARD = 14
PXI_FIFO_TAG_WVR = 15
PXI_FIFO_TAG_CTRDG_Ex = 16
PXI_MAX_FIFO_TAG = 32

PXI_FIFO_SUCCESS = 0
PXI_FIFO_FAIL_SEND_ERR = -1
PXI_FIFO_FAIL_SEND_FULL = -2
PXI_FIFO_FAIL_RECV_ERR = -3
PXI_FIFO_FAIL_RECV_EMPTY = -4
PXI_FIFO_NO_CALLBACK_ENTRY = -5

PXI_FIFO_SUCCESS = 0
PXI_FIFO_FAIL_SEND_ERR = -1
PXI_FIFO_FAIL_SEND_FULL = -2
PXI_FIFO_FAIL_RECV_ERR = -3
PXI_FIFO_FAIL_RECV_EMPTY = -4
PXI_FIFO_NO_CALLBACK_ENTRY = -5

PXIFifoCallback = u32
PXIFifoEmtpyCallback = u32
PXIFifoStatus = c_int
PXIFifoTag = c_int
RTCPxiResult = c_int


class PXIFifoMessage(Union):
    _fields_ = [
        ('e', struct__unnamed_at__Users_blakemoody_dev_mariokart_ml_mkds_c_src_stub_includes_nitro_pxi_common_fifo_h_137_5_),
        ('raw', u32),
    ]

class struct__unnamed_at__Users_blakemoody_dev_mariokart_ml_mkds_c_src_stub_includes_nitro_pxi_common_fifo_h_137_5_(Structure):
    _fields_ = [
        ('tag', u32),
        ('err', u32),
        ('data', u32),
    ]
