from ctypes import *
from private.mkds_python_bindings.testing.types import *

GX_WND_PLANEMASK_NONE = 0
GX_WND_PLANEMASK_BG0 = 1
GX_WND_PLANEMASK_BG1 = 2
GX_WND_PLANEMASK_BG2 = 4
GX_WND_PLANEMASK_BG3 = 8
GX_WND_PLANEMASK_OBJ = 16

GX_WND_PLANEMASK_NONE = 0
GX_WND_PLANEMASK_BG0 = 1
GX_WND_PLANEMASK_BG1 = 2
GX_WND_PLANEMASK_BG2 = 4
GX_WND_PLANEMASK_BG3 = 8
GX_WND_PLANEMASK_OBJ = 16

GX_BLEND_PLANEMASK_NONE = 0
GX_BLEND_PLANEMASK_BG0 = 1
GX_BLEND_PLANEMASK_BG1 = 2
GX_BLEND_PLANEMASK_BG2 = 4
GX_BLEND_PLANEMASK_BG3 = 8
GX_BLEND_PLANEMASK_OBJ = 16
GX_BLEND_PLANEMASK_BD = 32

GX_BLEND_PLANEMASK_NONE = 0
GX_BLEND_PLANEMASK_BG0 = 1
GX_BLEND_PLANEMASK_BG1 = 2
GX_BLEND_PLANEMASK_BG2 = 4
GX_BLEND_PLANEMASK_BG3 = 8
GX_BLEND_PLANEMASK_OBJ = 16
GX_BLEND_PLANEMASK_BD = 32

GXBlendPlaneMask = c_int
GXWndPlaneMask = c_int


class GXWndPlane(Structure):
    _fields_ = [
        ('planeMask', u8),
        ('effect', u8),
        ('_reserve', u8),
    ]
