from ctypes import *
from private.mkds_python_bindings.testing.fx import *
from private.mkds_python_bindings.testing.types import *

GX_MTXMODE_PROJECTION = 0
GX_MTXMODE_POSITION = 1
GX_MTXMODE_POSITION_VECTOR = 2
GX_MTXMODE_TEXTURE = 3

GX_MTXMODE_PROJECTION = 0
GX_MTXMODE_POSITION = 1
GX_MTXMODE_POSITION_VECTOR = 2
GX_MTXMODE_TEXTURE = 3

GX_BEGIN_TRIANGLES = 0
GX_BEGIN_QUADS = 1
GX_BEGIN_TRIANGLE_STRIP = 2
GX_BEGIN_QUAD_STRIP = 3

GX_BEGIN_TRIANGLES = 0
GX_BEGIN_QUADS = 1
GX_BEGIN_TRIANGLE_STRIP = 2
GX_BEGIN_QUAD_STRIP = 3

GX_SORTMODE_AUTO = 0
GX_SORTMODE_MANUAL = 1

GX_SORTMODE_AUTO = 0
GX_SORTMODE_MANUAL = 1

GX_BUFFERMODE_Z = 0
GX_BUFFERMODE_W = 1

GX_BUFFERMODE_Z = 0
GX_BUFFERMODE_W = 1

GX_LIGHTMASK_NONE = 0
GX_LIGHTMASK_0 = 1
GX_LIGHTMASK_1 = 2
GX_LIGHTMASK_01 = 3
GX_LIGHTMASK_2 = 4
GX_LIGHTMASK_02 = 5
GX_LIGHTMASK_12 = 6
GX_LIGHTMASK_012 = 7
GX_LIGHTMASK_3 = 8
GX_LIGHTMASK_03 = 9
GX_LIGHTMASK_13 = 10
GX_LIGHTMASK_013 = 11
GX_LIGHTMASK_23 = 12
GX_LIGHTMASK_023 = 13
GX_LIGHTMASK_123 = 14
GX_LIGHTMASK_0123 = 15

GX_LIGHTMASK_NONE = 0
GX_LIGHTMASK_0 = 1
GX_LIGHTMASK_1 = 2
GX_LIGHTMASK_01 = 3
GX_LIGHTMASK_2 = 4
GX_LIGHTMASK_02 = 5
GX_LIGHTMASK_12 = 6
GX_LIGHTMASK_012 = 7
GX_LIGHTMASK_3 = 8
GX_LIGHTMASK_03 = 9
GX_LIGHTMASK_13 = 10
GX_LIGHTMASK_013 = 11
GX_LIGHTMASK_23 = 12
GX_LIGHTMASK_023 = 13
GX_LIGHTMASK_123 = 14
GX_LIGHTMASK_0123 = 15

GX_POLYGONMODE_MODULATE = 0
GX_POLYGONMODE_DECAL = 1
GX_POLYGONMODE_TOON = 2
GX_POLYGONMODE_SHADOW = 3

GX_POLYGONMODE_MODULATE = 0
GX_POLYGONMODE_DECAL = 1
GX_POLYGONMODE_TOON = 2
GX_POLYGONMODE_SHADOW = 3

GX_CULL_ALL = 0
GX_CULL_FRONT = 1
GX_CULL_BACK = 2
GX_CULL_NONE = 3

GX_CULL_ALL = 0
GX_CULL_FRONT = 1
GX_CULL_BACK = 2
GX_CULL_NONE = 3

GX_POLYGON_ATTR_MISC_NONE = 0
GX_POLYGON_ATTR_MISC_XLU_DEPTH_UPDATE = 2048
GX_POLYGON_ATTR_MISC_FAR_CLIPPING = 4096
GX_POLYGON_ATTR_MISC_DISP_1DOT = 8192
GX_POLYGON_ATTR_MISC_DEPTHTEST_DECAL = 16384
GX_POLYGON_ATTR_MISC_FOG = 32768

GX_POLYGON_ATTR_MISC_NONE = 0
GX_POLYGON_ATTR_MISC_XLU_DEPTH_UPDATE = 2048
GX_POLYGON_ATTR_MISC_FAR_CLIPPING = 4096
GX_POLYGON_ATTR_MISC_DISP_1DOT = 8192
GX_POLYGON_ATTR_MISC_DEPTHTEST_DECAL = 16384
GX_POLYGON_ATTR_MISC_FOG = 32768

GX_TEXREPEAT_NONE = 0
GX_TEXREPEAT_S = 1
GX_TEXREPEAT_T = 2
GX_TEXREPEAT_ST = 3

GX_TEXREPEAT_NONE = 0
GX_TEXREPEAT_S = 1
GX_TEXREPEAT_T = 2
GX_TEXREPEAT_ST = 3

GX_TEXFLIP_NONE = 0
GX_TEXFLIP_S = 1
GX_TEXFLIP_T = 2
GX_TEXFLIP_ST = 3

GX_TEXFLIP_NONE = 0
GX_TEXFLIP_S = 1
GX_TEXFLIP_T = 2
GX_TEXFLIP_ST = 3

GX_TEXSIZE_S8 = 0
GX_TEXSIZE_S16 = 1
GX_TEXSIZE_S32 = 2
GX_TEXSIZE_S64 = 3
GX_TEXSIZE_S128 = 4
GX_TEXSIZE_S256 = 5
GX_TEXSIZE_S512 = 6
GX_TEXSIZE_S1024 = 7

GX_TEXSIZE_S8 = 0
GX_TEXSIZE_S16 = 1
GX_TEXSIZE_S32 = 2
GX_TEXSIZE_S64 = 3
GX_TEXSIZE_S128 = 4
GX_TEXSIZE_S256 = 5
GX_TEXSIZE_S512 = 6
GX_TEXSIZE_S1024 = 7

GX_TEXSIZE_T8 = 0
GX_TEXSIZE_T16 = 1
GX_TEXSIZE_T32 = 2
GX_TEXSIZE_T64 = 3
GX_TEXSIZE_T128 = 4
GX_TEXSIZE_T256 = 5
GX_TEXSIZE_T512 = 6
GX_TEXSIZE_T1024 = 7

GX_TEXSIZE_T8 = 0
GX_TEXSIZE_T16 = 1
GX_TEXSIZE_T32 = 2
GX_TEXSIZE_T64 = 3
GX_TEXSIZE_T128 = 4
GX_TEXSIZE_T256 = 5
GX_TEXSIZE_T512 = 6
GX_TEXSIZE_T1024 = 7

GX_TEXFMT_NONE = 0
GX_TEXFMT_A3I5 = 1
GX_TEXFMT_PLTT4 = 2
GX_TEXFMT_PLTT16 = 3
GX_TEXFMT_PLTT256 = 4
GX_TEXFMT_COMP4x4 = 5
GX_TEXFMT_A5I3 = 6
GX_TEXFMT_DIRECT = 7

GX_TEXFMT_NONE = 0
GX_TEXFMT_A3I5 = 1
GX_TEXFMT_PLTT4 = 2
GX_TEXFMT_PLTT16 = 3
GX_TEXFMT_PLTT256 = 4
GX_TEXFMT_COMP4x4 = 5
GX_TEXFMT_A5I3 = 6
GX_TEXFMT_DIRECT = 7

GX_TEXPLTTCOLOR0_USE = 0
GX_TEXPLTTCOLOR0_TRNS = 1

GX_TEXPLTTCOLOR0_USE = 0
GX_TEXPLTTCOLOR0_TRNS = 1

GX_TEXGEN_NONE = 0
GX_TEXGEN_TEXCOORD = 1
GX_TEXGEN_NORMAL = 2
GX_TEXGEN_VERTEX = 3

GX_TEXGEN_NONE = 0
GX_TEXGEN_TEXCOORD = 1
GX_TEXGEN_NORMAL = 2
GX_TEXGEN_VERTEX = 3

GX_LIGHTID_0 = 0
GX_LIGHTID_1 = 1
GX_LIGHTID_2 = 2
GX_LIGHTID_3 = 3

GX_LIGHTID_0 = 0
GX_LIGHTID_1 = 1
GX_LIGHTID_2 = 2
GX_LIGHTID_3 = 3

GXBegin = c_int
GXBufferMode = c_int
GXCull = c_int
GXLightId = c_int
GXLightMask = c_int
GXMtxMode = c_int
GXPolygonAttrMisc = c_int
GXPolygonMode = c_int
GXSortMode = c_int
GXSt = c_int
GXTexFlip = c_int
GXTexFmt = c_int
GXTexGen = c_int
GXTexPlttBaseParam = c_int
GXTexPlttColor0 = c_int
GXTexRepeat = c_int
GXTexSizeS = c_int
GXTexSizeT = c_int
VecVtx10 = c_int
VecVtxDiff = c_int


class GXBoxTestParam(Union):
    _fields_ = [
        ('val', (u32 * 3)),
    ]

class struct__anonymous_at__Users_blakemoody_dev_mariokart_ml_mkds_c_src_stub_includes_nitro_gx_g3_h_512_5_(Structure):
    _fields_ = [
        ('x', fx16),
        ('y', fx16),
        ('z', fx16),
        ('width', fx16),
        ('height', fx16),
        ('depth', fx16),
    ]

class GXDLInfo(Structure):
    _fields_ = [
        ('curr_cmd', u32), #POINTER(u8)),
        ('curr_param', u32), #POINTER(u32)),
        ('bottom', u32), #POINTER(u32)),
        ('length', u32),
        ('param0_cmd_flg', BOOL),
    ]
