from ctypes import *
SND_CHANNEL_OUT_MIXER = 0
SND_CHANNEL_OUT_BYPASS = 1

SND_CHANNEL_OUT_MIXER = 0
SND_CHANNEL_OUT_BYPASS = 1

SND_OUTPUT_MIXER = 0
SND_OUTPUT_CHANNEL1 = 1
SND_OUTPUT_CHANNEL3 = 2
SND_OUTPUT_CHANNEL1_3 = 3

SND_OUTPUT_MIXER = 0
SND_OUTPUT_CHANNEL1 = 1
SND_OUTPUT_CHANNEL3 = 2
SND_OUTPUT_CHANNEL1_3 = 3

SNDChannelOut = c_int
SNDOutput = c_int

