from ctypes import *
from private.mkds_python_bindings.testing.types import *

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

INPUT_REC_STATE_IDLE = 0
INPUT_REC_STATE_RECORDING = 1
INPUT_REC_STATE_PLAYING = 2
INPUT_REC_STATE_BUFFER_FULL = 3

InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int
InputRecState = c_int


class input_rec_recording_entry_t(Structure):
    _fields_ = [
        ('keys', u8),
        ('duration', u8),
    ]

class input_rec_recording_t(Structure):
    _fields_ = [
        ('dataLength', u32),
        ('entries', (input_rec_recording_entry_t * 1764)),
    ]

class input_rec_t(Structure):
    _fields_ = [
        ('recording', u32), #POINTER(input_rec_recording_t)),
        ('curEntry', u16),
        ('waitCounter', u16),
        ('state', InputRecState),
        ('isBufferClear', BOOL),
    ]
