from ctypes import *
from private.mkds_python_bindings.testing.fx import *
from private.mkds_python_bindings.testing.light import *
from private.mkds_python_bindings.testing.sfx import *
from private.mkds_python_bindings.testing.types import *

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

ITEM_KOURA_G = 0
ITEM_KOURA_R = 1
ITEM_BANANA = 2
ITEM_KINOKO = 3
ITEM_STAR = 4
ITEM_KOURA_W = 5
ITEM_THUNDER = 6
ITEM_F_BOX = 7
ITEM_ITEMBOX = 8
ITEM_BOMB = 9
ITEM_GESSO = 10
ITEM_TERESA = 11
ITEM_KINOKO_P = 12
ITEM_KILLER = 13
ITEM_COUNT = 14

MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int
MKDSItem = c_int


class it_itemconfig_t(Structure):
    _fields_ = [
        ('enabled', BOOL),
        ('wifiEnabled', BOOL),
        ('type', MKDSItem),
        ('count', u32),
        ('field10', u32),
        ('field14', u32),
        ('activateFunc', u32),
    ]

class it_item_def_t(Structure):
    _fields_ = [
        ('instanceSize', u32),
        ('limit', u32),
        ('field8', u32),
        ('instanceCount', c_int),
        ('field10', c_int),
        ('loadFunc', u32),
        ('initInstanceFunc', u32),
        ('field1C', u32),
        ('field20', u32),
        ('field24', u32),
        ('updateFunc', u32),
        ('renderFunc', u32),
        ('visibilityFlagCalcFunc', u32),
        ('field34', u32),
        ('field38', u32),
        ('destroyInstFunc', u32),
        ('field40', c_int),
        ('field44', c_int),
        ('field48', u32),
        ('field4C', c_int),
        ('field50', u32),
        ('gap54', u32),
        ('field58', u32),
        ('field5C', c_int),
        ('field60', c_int),
        ('colSphereRadius', c_int),
        ('sphereRadius1', c_int),
        ('sphereRadius2', c_int),
        ('field70', c_int),
        ('scale', c_int),
        ('field78', c_int),
        ('field7C', c_int),
        ('field80', c_int),
        ('field84', c_int),
        ('field88', c_int),
        ('gap8C', u32),
        ('field90', c_int),
        ('field94', c_int),
        ('field98', c_int),
        ('field9C', c_int),
        ('fieldA0', c_int),
        ('fieldA4', c_int),
    ]

class it_item_inst_t(Structure):
    _fields_ = [
        ('sfxEmitter', sfx_emitter_t),
        ('type', u32),
        ('field48', u32),
        ('field4C', u16),
        ('field4E', u16),
        ('position', VecFx32),
        ('velocity', VecFx32),
        ('scale', VecFx32),
        ('flags', u32),
        ('field78', u16),
        ('field7A', u16),
        ('light', light_t),
        ('lightPtr', u32), #POINTER(light_t)),
        ('mtx', MtxFx43),
        ('gapC4', (u8 * 12)),
        ('fieldD0', u32), #POINTER(VecFx32)),
        ('visibilityFlags', u32),
        ('alpha', s16),
        ('colEntryId', u16),
        ('fieldDC', u32),
        ('sphereSize', fx32),
        ('fieldE4', VecFx32),
        ('fieldF0', VecFx32),
        ('fieldFC', u32),
        ('field100', u32),
        ('field104', u32),
        ('field108', VecFx32),
        ('field114', u16),
        ('field116', u16),
        ('field118', u16),
        ('field11A', u16),
        ('field11C', u32),
        ('field120', u32),
        ('field124', u32),
        ('field128DriverMask', u8),
    ]

class it_itemset_t(Structure):
    _fields_ = [
        ('id', u32),
        ('instances', u32), #POINTER(it_item_inst_t)),
        ('totalInstanceCount', u32),
        ('itemParamsField10', u32),
        ('activeInstanceCount', u32),
        ('field14', u32),
        ('field18', u32),
        ('activeInstanceCount2', u32),
        ('limit', u32),
        ('renderFunc', u32),
        ('visibilityFlagCalcFunc', u32),
        ('itemParamsField70', u32),
        ('scale', fx32),
        ('itemParamsField78', u32),
        ('itemParamsField5C', u32),
        ('itemParamsFieldA4', u32),
        ('renderingDisabled', BOOL),
    ]

class itnet_action_t_(Structure):
    _fields_ = [
        ('data', (u8 * 20)),
        ('itemType', MKDSItem),
        ('action', u32),
        ('field1C', u32),
    ]
