from ctypes import *
from private.mkds_python_bindings.testing.fx import *
from private.mkds_python_bindings.testing.types import *

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MOBJ_COLLISION_TYPE_NONE = 0
MOBJ_COLLISION_TYPE_SPHERE = 1
MOBJ_COLLISION_TYPE_SPHEROID = 2
MOBJ_COLLISION_TYPE_CYLINDER = 3
MOBJ_COLLISION_TYPE_BOX = 4
MOBJ_COLLISION_TYPE_CUSTOM = 5

MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
MObjCollisionType = c_int
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_driver_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_item_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32
mobj_config_sphere_collide_func_t = u32


class mobj_config_t(Structure):
    _fields_ = [
        ('driverCollideFunc', mobj_config_driver_collide_func_t),
        ('itemCollideFunc', mobj_config_item_collide_func_t),
        ('colType', MObjCollisionType),
        ('size', VecFx32),
        ('sphereCollideFunc', mobj_config_sphere_collide_func_t),
        ('providesPushback', BOOL),
        ('logicType', u32),
        ('driverHitSfxId', s32),
        ('itemHitSfxId', u32),
        ('nearClip', fx32),
        ('farClip', fx32),
        ('has3DModel', BOOL),
        ('sfxAudibleMaxCamYDiff', fx32),
        ('sfxAudibleMinCamYDiff', fx32),
    ]
