from ctypes import *
from private.mkds_python_bindings.testing.types import *

MIC_RESULT_SUCCESS = 0
MIC_RESULT_BUSY = 1
MIC_RESULT_ILLEGAL_PARAMETER = 2
MIC_RESULT_SEND_ERROR = 3
MIC_RESULT_INVALID_COMMAND = 4
MIC_RESULT_ILLEGAL_STATUS = 5
MIC_RESULT_FATAL_ERROR = 6
MIC_RESULT_MAX = 7

MIC_RESULT_SUCCESS = 0
MIC_RESULT_BUSY = 1
MIC_RESULT_ILLEGAL_PARAMETER = 2
MIC_RESULT_SEND_ERROR = 3
MIC_RESULT_INVALID_COMMAND = 4
MIC_RESULT_ILLEGAL_STATUS = 5
MIC_RESULT_FATAL_ERROR = 6
MIC_RESULT_MAX = 7

MIC_SAMPLING_TYPE_8BIT = 0
MIC_SAMPLING_TYPE_12BIT = 1
MIC_SAMPLING_TYPE_SIGNED_8BIT = 2
MIC_SAMPLING_TYPE_SIGNED_12BIT = 3
MIC_SAMPLING_TYPE_12BIT_FILTER_OFF = 4
MIC_SAMPLING_TYPE_SIGNED_12BIT_FILTER_OFF = 5
MIC_SAMPLING_TYPE_MAX = 6

MIC_SAMPLING_TYPE_8BIT = 0
MIC_SAMPLING_TYPE_12BIT = 1
MIC_SAMPLING_TYPE_SIGNED_8BIT = 2
MIC_SAMPLING_TYPE_SIGNED_12BIT = 3
MIC_SAMPLING_TYPE_12BIT_FILTER_OFF = 4
MIC_SAMPLING_TYPE_SIGNED_12BIT_FILTER_OFF = 5
MIC_SAMPLING_TYPE_MAX = 6

MIC_SAMPLING_RATE_8K = 4189
MIC_SAMPLING_RATE_11K = 3039
MIC_SAMPLING_RATE_16K = 2094
MIC_SAMPLING_RATE_22K = 1519
MIC_SAMPLING_RATE_32K = 1047
MIC_SAMPLING_RATE_LIMIT = 1024

MIC_SAMPLING_RATE_8K = 4189
MIC_SAMPLING_RATE_11K = 3039
MIC_SAMPLING_RATE_16K = 2094
MIC_SAMPLING_RATE_22K = 1519
MIC_SAMPLING_RATE_32K = 1047
MIC_SAMPLING_RATE_LIMIT = 1024

MICCallback = u32
MICResult = c_int
MICSamplingRate = c_int
MICSamplingType = c_int


class MICAutoParam(Structure):
    _fields_ = [
        ('type', MICSamplingType),
        ('buffer', u32),
        ('size', u32),
        ('rate', u32),
        ('loop_enable', BOOL),
        ('full_callback', MICCallback),
        ('full_arg', u32),
    ]
