from ctypes import *
from private.mkds_python_bindings.testing.fx import *
from private.mkds_python_bindings.testing.gxcommon import *
from private.mkds_python_bindings.testing.types import *

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_SHAPE_BOX = 0
NKM_AREA_SHAPE_CYLINDER = 1

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_AREA_TYPE_0 = 0
NKM_AREA_TYPE_CAMERA = 1
NKM_AREA_TYPE_MISSION_END = 2
NKM_AREA_TYPE_CLIP_AREA = 3
NKM_AREA_TYPE_ENEMY_RESPAWN_ROUTE = 4
NKM_AREA_TYPE_MISSION_RIVAL_PASS_AREA = 5

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_TYPE_0 = 0
NKM_CAME_TYPE_1 = 1
NKM_CAME_TYPE_2 = 2
NKM_CAME_TYPE_INTRO_TOP = 3
NKM_CAME_TYPE_INTRO_BOTTOM = 4
NKM_CAME_TYPE_5 = 5
NKM_CAME_TYPE_6 = 6
NKM_CAME_TYPE_INTRO_MG = 7
NKM_CAME_TYPE_MR_FINISH = 8

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKM_CAME_FIRST_INTRO_NONE = 0
NKM_CAME_FIRST_INTRO_TOP = 1
NKM_CAME_FIRST_INTRO_BOTTOM = 2

NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaShape = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMAreaType = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameIntroFirst = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int
NKMCameType = c_int


class nkm_header_t(Structure):
    _fields_ = [
        ('magic', u32),
        ('version', u16),
        ('headerLength', u16),
        ('offsets', (u32 * 17)),
    ]

class nkm_section_header_t(Structure):
    _fields_ = [
        ('magic', u32),
        ('count', u32),
    ]

class nkm_obji_entry_t(Structure):
    _fields_ = [
        ('position', VecFx32),
        ('rotation', VecFx32),
        ('scale', VecFx32),
        ('objectId', u16),
        ('pathId', s16),
        ('settings', (s16 * 7)),
        ('flags', s16),
        ('showsInTT', u16),
    ]

class nkm_obji_t(Structure):
    _fields_ = [
        ('header', nkm_section_header_t),
        ('entries', (nkm_obji_entry_t * 0)),
    ]

class nkm_path_entry_t(Structure):
    _fields_ = [
        ('id', u8),
        ('loop', u8),
        ('pointCount', u16),
    ]

class nkm_path_t(Structure):
    _fields_ = [
        ('header', nkm_section_header_t),
        ('entries', (nkm_path_entry_t * 0)),
    ]

class nkm_poit_entry_t(Structure):
    _fields_ = [
        ('position', VecFx32),
        ('pointIndex', u8),
        ('unknown1', u8),
        ('duration', s16),
    ]

class union__anonymous_at__Users_blakemoody_dev_mariokart_ml_mkds_c_src_race_mapData_nkm_h_66_5_(Union):
    _fields_ = [
        ('unknown2', u32),
    ]

class struct__anonymous_at__Users_blakemoody_dev_mariokart_ml_mkds_c_src_race_mapData_nkm_h_69_9_(Structure):
    _fields_ = [
        ('unknown2_s16', s16),
        ('unknown2_s16_hi', s16),
    ]

class nkm_poit_t(Structure):
    _fields_ = [
        ('header', nkm_section_header_t),
        ('entries', (nkm_poit_entry_t * 0)),
    ]

class nkm_stag_data_t(Structure):
    _fields_ = [
        ('courseId', u16),
        ('nrLaps', u16),
        ('polePosition', u8),
        ('fogEnabled', u8),
        ('fogTableGenMode', u8),
        ('fogSlope', u8),
        ('unknown2', (u8 * 8)),
        ('fogDensity', fx32),
        ('fogColor', u32),
        ('kclColors', (GXRgb * 4)),
        ('mobjFarClip', fx32),
        ('frustumFar', fx32),
    ]

class nkm_stag_t(Structure):
    _fields_ = [
        ('magic', u32),
        ('data', nkm_stag_data_t),
    ]

class nkm_ktps_entry_t(Structure):
    _fields_ = [
        ('position', VecFx32),
        ('rotation', VecFx32),
        ('padding', u16),
        ('index', s16),
    ]

class nkm_ktps_t(Structure):
    _fields_ = [
        ('header', nkm_section_header_t),
        ('entries', (nkm_ktps_entry_t * 0)),
    ]

class nkm_ktpj_entry_t(Structure):
    _fields_ = [
        ('position', VecFx32),
        ('rotation', VecFx32),
        ('enemyPointId', u16),
        ('itemPointId', u16),
        ('id', s16),
    ]

class nkm_ktpj_t(Structure):
    _fields_ = [
        ('header', nkm_section_header_t),
        ('entries', (nkm_ktpj_entry_t * 0)),
    ]

class nkm_ktp2_entry_t(Structure):
    _fields_ = [
        ('position', VecFx32),
        ('rotation', VecFx32),
        ('padding', u16),
        ('id', u16),
    ]

class nkm_ktp2_t(Structure):
    _fields_ = [
        ('header', nkm_section_header_t),
        ('entries', (nkm_ktp2_entry_t * 0)),
    ]

class nkm_ktpc_entry_t(Structure):
    _fields_ = [
        ('position', VecFx32),
        ('rotation', VecFx32),
        ('nextMepo', s16),
        ('id', u16),
    ]

class nkm_ktpc_t(Structure):
    _fields_ = [
        ('header', nkm_section_header_t),
        ('entries', (nkm_ktpc_entry_t * 0)),
    ]

class nkm_ktpm_entry_t(Structure):
    _fields_ = [
        ('position', VecFx32),
        ('rotation', VecFx32),
        ('padding', u16),
        ('id', s16),
    ]

class nkm_ktpm_t(Structure):
    _fields_ = [
        ('header', nkm_section_header_t),
        ('entries', (nkm_ktpm_entry_t * 0)),
    ]

class nkm_cpoi_entry_t(Structure):
    _fields_ = [
        ('x1', fx32),
        ('z1', fx32),
        ('x2', fx32),
        ('z2', fx32),
        ('sin', fx32),
        ('cos', fx32),
        ('distance', fx32),
        ('gotoSection', s16),
        ('startSection', s16),
        ('keyId', s16),
        ('respawnId', u8),
        ('flags', u8),
    ]

class nkm_cpoi_t(Structure):
    _fields_ = [
        ('header', nkm_section_header_t),
        ('entries', (nkm_cpoi_entry_t * 0)),
    ]

class nkm_cpat_entry_t(Structure):
    _fields_ = [
        ('start', u16),
        ('length', u16),
        ('next', (u8 * 3)),
        ('previous', (u8 * 3)),
        ('sectionOrder', u8),
    ]

class nkm_cpat_t(Structure):
    _fields_ = [
        ('header', nkm_section_header_t),
        ('entries', (nkm_cpat_entry_t * 0)),
    ]

class nkm_ipoi_entry_t(Structure):
    _fields_ = [
        ('position', VecFx32),
        ('radius', fx32),
        ('recalcIdx', u8),
    ]

class nkm_ipoi_entry_beta_t(Structure):
    _fields_ = [
        ('position', VecFx32),
        ('radius', fx32),
    ]

class nkm_ipoi_entry_pointer_t(Union):
    _fields_ = [
        ('final', u32), #POINTER(nkm_ipoi_entry_t)),
        ('beta', u32), #POINTER(nkm_ipoi_entry_beta_t)),
    ]

class nkm_ipoi_t(Structure):
    _fields_ = [
        ('header', nkm_section_header_t),
        ('entries', (nkm_ipoi_entry_t * 0)),
    ]

class nkm_ipat_entry_t(Structure):
    _fields_ = [
        ('start', u16),
        ('length', u16),
        ('next', (u8 * 3)),
        ('previous', (u8 * 3)),
        ('sectionOrder', s16),
    ]

class nkm_ipat_t(Structure):
    _fields_ = [
        ('header', nkm_section_header_t),
        ('entries', (nkm_ipat_entry_t * 0)),
    ]

class nkm_epoi_entry_settings_t(Structure):
    _fields_ = [
        ('drifting', u16),
        ('unknown1', u16),
        ('unknown2', u32),
    ]

class nkm_epoi_entry_t(Structure):
    _fields_ = [
        ('position', VecFx32),
        ('radius', fx32),
        ('settings', nkm_epoi_entry_settings_t),
    ]

class nkm_epoi_t(Structure):
    _fields_ = [
        ('header', nkm_section_header_t),
        ('entries', (nkm_epoi_entry_t * 0)),
    ]

class nkm_epat_entry_t(Structure):
    _fields_ = [
        ('start', u16),
        ('length', u16),
        ('next', (u8 * 3)),
        ('previous', (u8 * 3)),
        ('sectionOrder', s16),
    ]

class nkm_epat_t(Structure):
    _fields_ = [
        ('header', nkm_section_header_t),
        ('entries', (nkm_epat_entry_t * 0)),
    ]

class nkm_mepo_entry_settings_t(Structure):
    _fields_ = [
        ('drifting', u32),
        ('unknown1', u32),
    ]

class nkm_mepo_entry_t(Structure):
    _fields_ = [
        ('position', VecFx32),
        ('radius', fx32),
        ('settings', nkm_mepo_entry_settings_t),
    ]

class nkm_mepo_t(Structure):
    _fields_ = [
        ('header', nkm_section_header_t),
        ('entries', (nkm_mepo_entry_t * 0)),
    ]

class nkm_mepa_entry_t(Structure):
    _fields_ = [
        ('start', u16),
        ('length', u16),
        ('next', (u8 * 8)),
        ('previous', (u8 * 8)),
    ]

class nkm_mepa_t(Structure):
    _fields_ = [
        ('header', nkm_section_header_t),
        ('entries', (nkm_mepa_entry_t * 0)),
    ]

class nkm_area_entry_t(Structure):
    _fields_ = [
        ('position', VecFx32),
        ('length', VecFx32),
        ('xVector', VecFx32),
        ('yVector', VecFx32),
        ('zVector', VecFx32),
        ('param0', s16),
        ('param1', s16),
        ('enemyPointId', s16),
        ('shape', u8),
        ('cameraId', u8),
        ('type', u8),
        ('field45', u8),
        ('field46', u8),
        ('field47', u8),
    ]

class nkm_area_t(Structure):
    _fields_ = [
        ('header', nkm_section_header_t),
        ('entries', (nkm_area_entry_t * 0)),
    ]

class nkm_came_entry_t(Structure):
    _fields_ = [
        ('position', VecFx32),
        ('rotation', VecFx32),
        ('target1', VecFx32),
        ('target2', VecFx32),
        ('fovBegin', u16),
        ('fovBeginSin', fx16),
        ('fovBeginCos', fx16),
        ('fovEnd', u16),
        ('fovEndSin', fx16),
        ('fovEndCos', fx16),
        ('fovSpeed', s16),
        ('type', u16),
        ('pathId', s16),
        ('routeSpeed', s16),
        ('targetSpeed', u16),
        ('duration', u16),
        ('next', s16),
        ('introFirst', u8),
        ('unknown', u8),
    ]

class nkm_came_t(Structure):
    _fields_ = [
        ('header', nkm_section_header_t),
        ('entries', (nkm_came_entry_t * 0)),
    ]

class nkm_t(Structure):
    _fields_ = [
        ('header', nkm_header_t),
        ('obji', nkm_obji_t),
    ]
