from ctypes import *
from private.mkds_python_bindings.testing.types import *

TP_REQUEST_COMMAND_SAMPLING = 0
TP_REQUEST_COMMAND_AUTO_ON = 1
TP_REQUEST_COMMAND_AUTO_OFF = 2
TP_REQUEST_COMMAND_SET_STABILITY = 3
TP_REQUEST_COMMAND_AUTO_SAMPLING = 16

TP_REQUEST_COMMAND_SAMPLING = 0
TP_REQUEST_COMMAND_AUTO_ON = 1
TP_REQUEST_COMMAND_AUTO_OFF = 2
TP_REQUEST_COMMAND_SET_STABILITY = 3
TP_REQUEST_COMMAND_AUTO_SAMPLING = 16

TP_REQUEST_COMMAND_FLAG_SAMPLING = 1
TP_REQUEST_COMMAND_FLAG_AUTO_ON = 2
TP_REQUEST_COMMAND_FLAG_AUTO_OFF = 4
TP_REQUEST_COMMAND_FLAG_SET_STABILITY = 8

TP_REQUEST_COMMAND_FLAG_SAMPLING = 1
TP_REQUEST_COMMAND_FLAG_AUTO_ON = 2
TP_REQUEST_COMMAND_FLAG_AUTO_OFF = 4
TP_REQUEST_COMMAND_FLAG_SET_STABILITY = 8

TP_RESULT_SUCCESS = 0
TP_RESULT_INVALID_PARAMETER = 1
TP_RESULT_ILLEGAL_STATUS = 2
TP_RESULT_EXCLUSIVE = 3
TP_RESULT_PXI_BUSY = 4

TP_RESULT_SUCCESS = 0
TP_RESULT_INVALID_PARAMETER = 1
TP_RESULT_ILLEGAL_STATUS = 2
TP_RESULT_EXCLUSIVE = 3
TP_RESULT_PXI_BUSY = 4

TP_STATE_READY = 0
TP_STATE_SAMPLING = 1
TP_STATE_AUTO_SAMPLING = 2
TP_STATE_AUTO_WAIT_END = 3

TP_STATE_READY = 0
TP_STATE_SAMPLING = 1
TP_STATE_AUTO_SAMPLING = 2
TP_STATE_AUTO_WAIT_END = 3

TPRecvCallback = u32
TPRequestCommand = c_int
TPRequestCommandFlag = c_int
TPRequestResult = c_int
TPState = c_int


class TPData(Structure):
    _fields_ = [
        ('x', u16),
        ('y', u16),
        ('touch', u16),
        ('validity', u16),
    ]

class NvTpData(Structure):
    _fields_ = [
        ('x0', s16),
        ('y0', s16),
        ('xDotSize', s16),
        ('yDotSize', s16),
    ]
