from ctypes import *
WVR_RESULT_SUCCESS = 0
WVR_RESULT_OPERATING = 1
WVR_RESULT_DISABLE = 2
WVR_RESULT_INVALID_PARAM = 3
WVR_RESULT_FIFO_ERROR = 4
WVR_RESULT_ILLEGAL_STATUS = 5
WVR_RESULT_VRAM_LOCKED = 6
WVR_RESULT_FATAL_ERROR = 7
WVR_RESULT_MAX = 8

WVR_RESULT_SUCCESS = 0
WVR_RESULT_OPERATING = 1
WVR_RESULT_DISABLE = 2
WVR_RESULT_INVALID_PARAM = 3
WVR_RESULT_FIFO_ERROR = 4
WVR_RESULT_ILLEGAL_STATUS = 5
WVR_RESULT_VRAM_LOCKED = 6
WVR_RESULT_FATAL_ERROR = 7
WVR_RESULT_MAX = 8

WVRResult = c_int

